### ISSUE TITLE
idea: allow jumping to different buffers

### ISSUE THREAD

**Issue by doda-zz** [winterTTr/ace-jump-mode#10]
instead of stopping at the end of the current buffer, keep drawing characters into any following buffers. i imagine this would be a super powerful feature :) 

maybe with some kind of modifier before-hand? although i think it'd be preferable out of the box

**Comment by winterTTr** [comment]
I never thought this idea before. But it indeed sounds pretty cool !!!!
I will try to do some experiment now to see if I can do that, thanks so much for this great suggestion !!!!

**Comment by winterTTr** [comment]
The new global ace jump is under development. You can check under the branch FB-Global-AJ.
I have investigated some basic problems and it seems there is no blocking issues right now. 
Please wait for maybe several weeks to let me complete it. :-)

**Comment by doda-zz** [comment]
this is totally cool :) i look forward to using it

**Comment by ced4git** [comment]
That would be totally lovely...  Something allowing to ace-jump to any buffer in any frame would be amazingly powerful.  Do you plan to make it work for any buffer in the current frame only or for any buffer in any frame? In any case you can be sure you'll have a lot of users as soon as this comes out! Like doda, I'm looking forward to using it!

**Comment by winterTTr** [comment]
Yes, actually, right now, most of the code should have been completed. But, I still need to do some test to verify the all the function can indeed work well.
Of course, finally, you can use it across any frame( created by C-x 5 ), and any window. I would like make this as a default behavior when I complete the code. There will also be a variable that control how ace jump work if anyone want it to only work for the current window or frame. 
So please just wait for a little while :-)

**Comment by winterTTr** [comment]
ace jump mode2.0 preview comes out.
If you want to have a try : 

> git clone https://github.com/winterTTr/ace-jump-mode.git 
> git checkout FB-Global-AJ 

I will continue to update the documentation and fix some bugs that may comes from some users, after that I will merge the stable release version to master branch.

**Comment by ced4git** [comment]
Amazing...  The FB-Global-AJ branch seems to be working fine for me so far.  Shall report if I find anything.

**Comment by doda-zz** [comment]
works very well! I will report if I find any bugs but this feels like a total game-changer. :D

**Comment by winterTTr** [comment]
Hi, doda, thanks so much for your great suggestion, which make 2.0 version come out.
Right now, I have already merge the feature branch back to master, so I think we can close this issue right now.
I will continue to fix any problem in 2.0RC on master branch, and 2.0 release will come soon

**Comment by doda-zz** [comment]
Sure we can close, thanks for ace-jump-mode :)
