### ISSUE TITLE
doesnt register . as jumpable character

### ISSUE THREAD

**Issue by doda-zz** [winterTTr/ace-jump-mode#13]
```
a .b
a.b
```

only recognizes the second `.` and turns to

```
a .b
aab
```

**Comment by winterTTr** [comment]
Thanks, I will trace this problem.

**Comment by winterTTr** [comment]
https://github.com/winterTTr/ace-jump-mode/commit/26082dc11fe3c4faac96c2e21236c0a3ee9bf654
I have fixed this problem right now, you can refer this commit for some detail if you are interested.

BTW,
the new commit right now only apply to the FB-Global-AJ branch, which is for ace jump mode 2.0 release recently.

**Comment by winterTTr** [comment]
As this problem is fixed right now, so I would like to close this.
If you have any other suggestion or bug, I think we can open a new ticket for that.

**Comment by doda-zz** [comment]
hey, i just got to trying it out, thanks for fixing the bug!
