### ISSUE TITLE
Letters in words prefixed with a $ aren't matched

### ISSUE THREAD

**Issue by jonashelgemo** [winterTTr/ace-jump-mode#19]
PHP example:

$abcd->abcde;
abcd->abcde;

Searching for 'a' in the above example gets 3 matches and not 4 as expected (the 'a' in $abcd is not matched). This is kind of a problem as all variables in PHP are prefixed with a '$'.

**Comment by winterTTr** [comment]
I have tried your example here, and the a after "$" can be selected( highlighted ), both for "word mode" and "char mode". So, could you verify that you are using the latest version of ace jump mode?

If yes, one possible reason may be related to the mode you're using and how that mode define "word" syntax? Could you tell me which mode you are using?

**Comment by jonashelgemo** [comment]
You are right! It works in both word and char mode but not in regular ace-jump-mode. Sorry about the confusion, and thanks for the quick reply. Loving ace-jump mode by the way!
