### ISSUE TITLE
Use ace-jump-mode as motion in evil-mode

### ISSUE THREAD

**Issue by expez** [winterTTr/ace-jump-mode#20]
Would it be possible to use ace-jump-mode as a motion in evil-mode?

**Comment by ghost** [comment]
You need a recursive-edit. Something like this may work:

``` cl
(define-key global-map (kbd "C-c SPC") 'my-ace-jump-char-mode)
(define-key global-map (kbd "C-c l") 'my-ace-jump-line-mode)

(evil-define-motion my-ace-jump-char-mode (count)
  :type exclusive
  (ace-jump-mode 1)
  (recursive-edit))

(evil-define-motion my-ace-jump-line-mode (count)
  :type line
  (ace-jump-line-mode)
  (recursive-edit))

(add-hook 'ace-jump-mode-end-hook 'exit-recursive-edit)
```

But you should be aware of the following issues:
1. calling ace-jump-mode with a prefix-argument does not work when called in operator-state. The reason is that the prefix argument is eaten by evil ;)
2. there is no safe-guard against jumps to other windows
3. the repeat-system will not work properly (and propably be confused) with motions defined by ace-jump-mode. Those jumps are very context dependent, thus very difficult to repeat right.

Also note that I do not use ace-jump-mode myself, so this code is heavily untested and propably full of bugs ;)

**Comment by expez** [comment]
Thanks for looking into this.  This solution, with these caveats, works fine for my intended use.  

While I was sleeping @cofi posted the following implementation of @lyro's advice to Evil's IRC channel:

``` cl
(evil-define-motion evil-ace-jump-char-mode (count)
  :type exclusive
  (ace-jump-mode 5)
  (recursive-edit))

(evil-define-motion evil-ace-jump-line-mode (count)
  :type line
  (ace-jump-mode 9)
  (recursive-edit))

(evil-define-motion evil-ace-jump-word-mode (count)
  :type exclusive
  (ace-jump-mode 1)
  (recursive-edit))

(evil-define-motion evil-ace-jump-char-direct-mode (count)
  :type inclusive
  (ace-jump-mode 5)
  (forward-char 1)
  (recursive-edit))

(add-hook 'ace-jump-mode-end-hook 'exit-recursive-edit)
```

The evil-ace-jump-char-direct-mode motion works like `f` and evil-ace-jump-char-mode works like `t`.  

Hopefully someone else interested in this can find this issue through google.

**Comment by winterTTr** [comment]
Hi @Expez,

Actually, I am also an user of evil, although I do not go deep into it so much.
I am just curious about why we need evil-define-motion here, I am always use ace-jump-mode directly under evil, and there should be no big problem until now.

I just add evil-normal-state-map a key map to trigger ace-jump-mode.

So comparing to my way, could you explain more detail about your purpose for these code snippet? 
That would be great help for people to understand the scenarios it apply to, thanks :-)

**Comment by expez** [comment]
The code snippets above makes it possible to use ace-jump as a motion in Evil.  This means we can use ace-jump in combination with the well-known verbs from vim like c (change), d (delete) etc. 

For example to delete a few lines I can do:

d `evil-ace-jump-line-mode`, causing the ace-jump overlay to appear for me to select up to which line I want to delete.

Or let's say I'm at the beginning of the line and want to change up to some letter x.  Instead of counting occurances of x's and use `ctx` I can do:

c `evil-ace-jump-char-mode`, and use use ace-jump to indicate which occurance of x I want to change to.

Just adding a key to evil-normal-state-map will let you jump around--and ease navigation--but it won't aid you when you want to edit text.

**Comment by winterTTr** [comment]
OK, I see, the main purpose is for combination in evil, I never try to use it like this before, and it's great!!
Thanks for your code snippet, I will also try to add it to my init file :-)
