### ISSUE TITLE
FlyCheck take precedence over Ace Jump

### ISSUE THREAD

**Issue by r-darwish** [winterTTr/ace-jump-mode#21]
When FlyCheck marks an error or a note, letters in the marked line won't change the color when Ace Jump is activated

![normal](https://f.cloud.github.com/assets/1383193/106708/26443d2a-6a08-11e2-88a7-b3736d1cdea3.png)

Trying to jump to 'b':
![ace](https://f.cloud.github.com/assets/1383193/106709/2ab15adc-6a08-11e2-9020-e7feb57d4260.png)

**Comment by winterTTr** [comment]
OK, i will try to investigate that, thanks for your reporting.
