### ISSUE TITLE
acejump mess Evil's evil-repeat command (the dot command)

### ISSUE THREAD

**Issue by Dewdrops** [winterTTr/ace-jump-mode#25]
I've been using acejump with Evil for months, and it saves lots of my time. Thanks for your fabulous work !

I find acejump cannot cooperate with Evil's evil-repeat(.) command well. That is, if I edit text somewhere, then acejump to another place and invoke evil-repeat by press ".", instead of  repeating my edit operation, nothing will happen. I think it will be better if acejump commands work like Evil's motion commands.

I use acejump 2.0 and Evil 1.0, with Emacs 24.3.1 in Ubuntu.

**Comment by winterTTr** [comment]
I am also a evil user, this is indeed a problem, I will try to solve it recently.

**Comment by Dewdrops** [comment]
I've also reported this bug to Evil's developers and this problem has been solved.

Details in [https://bitbucket.org/lyro/evil/issue/313/evils-acejump-integration-doesnt-work](https://bitbucket.org/lyro/evil/issue/313/evils-acejump-integration-doesnt-work)

**Comment by winterTTr** [comment]
@Dewdrops 
I am kinda busy recently, so I do not touch any bugs. Sorry for that.
Thanks for your reports and I am also very glad that evil have fixed for ace jump.
