### ISSUE TITLE
Characters after non-ASCII aren't targeted

### ISSUE THREAD

**Issue by reactormonk** [winterTTr/ace-jump-mode#30]
Given the text

```
drüüedriissgi
```

When I call `ace-jump-mode` with `d`, it finds the first `d`, but not
the second one. So I can't jump to it.

**Comment by winterTTr** [comment]
I tried your example, I think you should using the `word mode`, not `char mode`, the `word mode` will only mark the position by word.
Right now, C-c SPC will trigger the `word mode` by default. You need to add prefix `C-u` to start the `char mode`

More detail, refer here:
https://github.com/winterTTr/ace-jump-mode/wiki#how-to-use-it

**Comment by pavlo-alkhimov** [comment]
Shouldn't the issue be closed?

**Comment by winterTTr** [comment]
@paul-alkhimov Yes :-)
