### ISSUE TITLE
Overlay does not clear if char mode is invoked instead of choosing a letter

### ISSUE THREAD

**Issue by brianhou** [winterTTr/ace-jump-mode#34]
To reproduce this, jump somewhere with any mode (char, word, line) and instead of selecting a destination, call char mode with `C-c SPC`.

I think the relevant chunk of code is lines 664-670, when overriding the local keymap. My guess is that the shortcut `C-c C-c` for quick exchange is to blame. When I change that to `C-c`, everything seems to be fine.

**Comment by winterTTr** [comment]
Fixed and close.
