### ISSUE TITLE
Ace-Jump-Mode gets confused when the same buffer is in two windows

### ISSUE THREAD

**Issue by squid-lee** [winterTTr/ace-jump-mode#39]
If I have the same buffer open in more than one window (in the same or different frames), and then attempt to jump to a character visible in both windows, picking the jump option which keeps me in the same window, ace-jump goes to the wrong place.

e.g. If P is the point in window 1, and I choose to jump to a letter, I get two labels X (in window 1) and Y (in window 2).
If I choose x (same window as the point), ace-jump will go to somewhere that is not X. If I choose Y everything is okay.

**Comment by winterTTr** [comment]
OK, I will check this problem

**Comment by philc** [comment]
I couldn't reproduce this problem with the latest ace jump using ace-jump-word-mode.

**Comment by squid-lee** [comment]
Agreed. Seems to be solved.
