### ISSUE TITLE
Clearing overlay causes windows to jump unnecessarily

### ISSUE THREAD

**Issue by brianhou** [winterTTr/ace-jump-mode#40]
If I have two windows visiting the same buffer and I try to jump in one window, the other window shifts to view the same thing. So if I'm trying to look at two different parts of a file and I jump to a character, then both windows are now viewing the same lines. This seems to happen after the overlay clears.

**Comment by winterTTr** [comment]
Sorry for the late response. Life is busy.
This fix will resolve the your issue. Thanks for your reporting.

https://github.com/winterTTr/ace-jump-mode/commit/adffa3d289957f103a0cf0f6a963369b0c0ee4f6

**Comment by maxhgerlach** [comment]
Very nice, this seems to work fine now!
