### ISSUE TITLE
Two windows showing different parts of the same buffer

### ISSUE THREAD

**Issue by maxhgerlach** [winterTTr/ace-jump-mode#53]
If I have two windows, each showing a different portion of the same buffer, and then use ace-jump-mode to move the point in one of them, this works well, but the other window scrolls close to this position as well. That side-effect is rather unfortunate as I usually have had the other part visible for context.

**Comment by maxhgerlach** [comment]
Ah, this has been reported before: https://github.com/winterTTr/ace-jump-mode/issues/40

**Comment by maxhgerlach** [comment]
`(setq ace-jump-mode-scope 'window)` is a workaround.

**Comment by winterTTr** [comment]
This change will fix the issue you mentioned.
Thanks for your report :-) 
Enjoy AJ.
https://github.com/winterTTr/ace-jump-mode/commit/adffa3d289957f103a0cf0f6a963369b0c0ee4f6
