### ISSUE TITLE
Lisp error: (invalid-function "motion") on Cygwin Emacs

### ISSUE THREAD

**Issue by fniessen** [winterTTr/ace-jump-mode#57]
When running GNU Emacs 24.3.1 (i686-pc-cygwin) of 2013-08-14 on moufang, I get this backtrace:

Debugger entered--Lisp error: (invalid-function "motion")
  "motion"("location" "cursor")
  byte-code("\300\301\302\303\304\305\306\307\310\311\312\"&\207" [define-package "ace-jump-mode" "20140616.115" "a quick cursor location minor mode for emacs" nil :url "https://github.com/winterTTr/ace-jump-mode/" :keywords "motion" "location" "cursor"] 11)
  load("/cygdrive/d/Users/fni/.emacs.d/elpa/ace-jump-mode-20140616.115/ace-jump-mode-pkg" nil t)
  package-load-descriptor("~/.emacs.d/elpa" "ace-jump-mode-20140616.115")
  package-maybe-load-descriptor("ace-jump-mode" "20140616.115" "~/.emacs.d/elpa")
  package-load-all-descriptors()
  package-initialize()
  command-line()
  normal-top-level()

IIUC, the problem is a missing quote in front of the list, in file ace-jump-mode-pkg.el.

Though, what I don't understand is why it works from other Emacs versions...

**Comment by syohex** [comment]
Which emacs version do you use to install `ace-jump-mode` ?
I suppose that you installed `ace-jump-mode` with other than Emacs 24.3.1.
And it may works if you reinstall ace-jump-mode with Emacs 24.3.1.

**Comment by fniessen** [comment]
I must have installed it under my Win32 Emacs binary (24.3.93.1).

Does that mean that you consider that there is no problem?

**Comment by syohex** [comment]
No. Byte-compiled file does not have compatibility between other emacs version.
Emacs 24.3.93.1 is pretest version of Emacs 24.4. So its byte-compiled files may not
work on Emacs 24.3.

If you use multiple emacs versions, I recommend you to use [cask](https://github.com/cask/cask).
`cask` install packages per Emacs version.

**Comment by fniessen** [comment]
I've tried first to recompile AceJump with the Cygwin Emacs, to be sure. Didn't work.

I then removed completely the ELC files. Still, Emacs does not run. See http://screencast.com/t/grAykjjfh.

So, no, it's sure it has nothing to do with the byte-compiled files.

What's the problem, then?

**Comment by fniessen** [comment]
Note that adding a quote after the keywords keyword does solve the problem...

**Comment by syohex** [comment]
`*-pkg.el` is generated by `package.el`. I generated pkg file with Emacs 24.3.1 and Emacs 24.4,
but I did not get same as yours. Your pkg file looks like 24.4, but pkg file generated by Emacs 24.4
is quoted correctly.

``` lisp
;; Emacs 24.3.1
(define-package "ace-jump-mode" "20140616.115" "a quick cursor location minor mode for emacs" (quote nil))
```

``` lisp
;; Emacs 24.4.50.1
(define-package "ace-jump-mode" "20140616.115" "a quick cursor location minor mode for emacs" 'nil :url "https://github.com/winterTTr/ace-jump-mode/" :keywords '("motion" "location" "cursor"))
```

Is this issue of Cygwin Emacs ?

**Comment by fniessen** [comment]
I got the exact same problem in many other "ELPA" packages
(Dired+, Helm, YASnippet, etc.) though not all (not in Dired-single,
Fuzzy, Idle-require to name a few).

Half wrong, half right. I had to delete the package-pkg.el(c) files, in
order to be able to launch Cygwin Emacs-w32. Dunno why the exact same
config works with native Emacs, and not with Cygwin, why both programs
go and fetch their packages at the same place on my file system...

I need more hints on this. Maybe things will clear up in the future?

**Comment by kaushalmodi** [comment]
I am having the same invalid-function "motion" issue on 64-bit Cygwin; running the last stable emacs 24.3. I don't get that issue on emacs 24.3.91 (latest pretest available on Cygwin). I deleted all the .elc files but still I get this problem. Any help?

**Update**: From syohex's explanation above, looks like it's best to delete the elpa folder when switching emacs versions, or use separate elpa folders for different versions.

**Comment by syohex** [comment]
I can't reproduce this issue with Cygwin's Emacs 24.3,2

I got `-pkg.el` file same as yours with Emacs 24.3.93.1.
So I think that you install some packages with Emacs 24.3.93.1 however
you run Emacs 24.3.1.

Would you check emacs version when you install some packages ?
And would you check that multiple emacs are installed on your platform ?

**Comment by kaushalmodi** [comment]
I figured out how to reproduce this issue.  The issue occurs if you first have emacs 24.3.9x installed, install this package from Melpa and then downgrade to 24.3.7. In doing so, the `-pkg.el` files don't get downgraded (which were created using emacs 24.3.9x.

So the solution is to use separate `/elpa` folders for emacs 24.3.9x and emacs 24.3.7.

This issue is resolved for me.

**Comment by fniessen** [comment]
Indeed, new évidences show that the problem comes from a bug in Emacs 24.3.93.1 when installing packages. Not only Ace Jump by the way.

Case is closed. Thanks for your help!
