### ISSUE TITLE
[Feature]  jump to the char at the same line

### ISSUE THREAD

**Issue by coldnew** [winterTTr/ace-jump-mode#8]
just a little hack to make jump to the char at the same line more easily

(defun  ace-jump-char-smae-line-mode  (query-char)
  "AceJump char mode in the same line"
  (interactive (list (read-char "Query Char:")))
  (if (ace-jump-query-char-p query-char)
      (progn
        (setq ace-jump-query-char query-char)
        (setq ace-jump-current-mode 'ace-jump-char-mode)
        ;; here's what I modify from ace-jump-char-mode
        (ace-jump-do (regexp-quote (make-string 1 query-char)) (point-at-bol) (point-at-eol) 
             ))
    (error "[AceJump] Non-printable char"))

**Comment by winterTTr** [comment]
Thanks for your suggestion.
Currently, I think we can easily change to the word in current line via the whole "screen" mode. And usually, that would not be very complicated. So in my opinion, I think it is kinda redundant to add a line mode separately.

Thanks for your suggestion all the same, and really happy that you can share your idea with me.
I am also look forward your suggestion in the future. If you also agree with me, I will close this issue.

**Comment by coldnew** [comment]
Well, this feature is grab from vim's easymotion plugin, but I think you are right :)
