### ISSUE TITLE
Move package to MELPA

### ISSUE THREAD

**Issue by geraldus** [winterTTr/ace-jump-mode#87]
Hi @winterTTr ! Have you considered moving `ace-jump` to **MELPA**?

**Comment by winterTTr** [comment]
If i remember correctly, to support some package system, it just need to add some of the specific header in file comments and upload it to the package system.

I remember I do something like this before, but I am not sure if it is used for MELPA or some other package system.

Let me confirm first.

**Comment by geraldus** [comment]
Emacs have built-in linter and it warns about all required package boilerplate if it's missing.  You can see that warnings with Flycheck.

**Comment by winterTTr** [comment]
I see the ace-jump already exist in MELPA

`all required package boilerplate if it's missing`
How can you see this warning? Personally, I do not use MELPA, so i am not sure if that is some warning package from MELPA.

Can you give more detail step?

**Comment by geraldus** [comment]
> I see the ace-jump already exist in MELPA

Oh, apologize!  Indeed it is.  Before I opened this issue I tried to find `ace-jump` in package list, but found only third party packages.  Now I've re-checked package list and found `ace-jump-mode` among installed packages.  Closing this.  Best wishes!

Thank you for this package (;

**Comment by winterTTr** [comment]
Enjoy it :-p
